### DISCUSSION TITLE
Unknown tag string in exportAlignments output

### DISCUSSION THREAD

**Discussion by racng** [milaboratory/mixcr#1103] [Q&A]
```bash
MiXCR v4.2.0 (built Thu Jan 26 11:40:26 PST 2023; rev=b0f194e0c6; branch=no_branch; host=fv-az477-60)
RepSeq.IO v1.7.0 (rev=36f4e4453f)
MiLib v2.3.0 (rev=0226f1da59)
Built-in V/D/J/C library: repseqio.v2.1
```
I exported alignments with the following arguments in the preset file to look at molecular and cell barcodes:
```
exportAlignments:
  chains: ALL
  fields:
    - field: "-tags"
      args: [ "Cell" ]
    - field: "-tags"
      args: [ "Molecule" ]
    - field: "-readIds"
```
Each field has the expected barcode value followed by a space and then some string (ex.  SSSSSS, >;<<<?). What is the meaning of the second string for each field?
Here are the first few lines from an example output:
``` 
tagValueCELL	tagValueUMI1	tagValueUMI2	tagValueUMI3	readId
ACTCTT SSSSSS	TCAGCT >;<<<?	TTTTAT A@@@BB	AGCGATTG AA?6543<	688
ACTCTT SSSSSS	TCAGCT >;<<<?	TTTTAT A@@@BB	AGCGATTG AA?6543<	68584
ACTCTT SSSSSS	ACACTA GFHHLI	TATGTC CAACBF	CACGTTCA JIHJHIIK	30245
ACTCTT SSSSSS	ACACTA GFHHLI	TATGTC CAACBF	CACGTTCA JIHJHIIK	98141
ACTCTT SSSSSS	ACACTA GFHHLI	AGAAAC DEGHID	TCACTTAT HGEEFFCD	23566
ACTCTT SSSSSS	ACACTA GFHHLI	AGAAAC DEGHID	TCACTTAT HGEEFFCD	45118
```
