### DISCUSSION TITLE
How to just align for constant region

### DISCUSSION THREAD

**Discussion by ShaowenJ** [milaboratory/mixcr#1346] [Q&A] [answered]
Dear Amazing Mixcr developers,

You guys are very helpful for us on setting the previous Nanopore long-read preset. The results look fantastic, but there are only 25% of all the reads have aligned successfully (It's a target pull-down library specific for TCR/BCR). We are wondering what are the unaligned reads come from. 
Is that a way I can just check if the reads can align to the constant region?

The preset I am using is: under version of v4.2.0
```
flags: []
pipeline:
- align
- assemble
- assembleContigs
- exportClones
align:
  species: mmu
  libraryName: default
  trimmingQualityThreshold: 0
  trimmingWindowSize: 0
  chains: ALL
  replaceWildcards: true
  overlapPairedReads: true
  bamDropNonVDJ: false
  writeFailedAlignments: false
  tagPattern: null
  tagUnstranded: false
  tagMaxBudget: 10.0
  sampleTable: null
  splitBySample: false
  inferSampleTable: false
  readIdAsCellTag: false
  limit: null
  parameters:
    vParameters:
      geneFeatureToAlign: VTranscriptWithP
      minSumScore: 150
      relativeMinScore: 0.97
      parameters:
        type: kaligner2
        mapperNValue: 14
        mapperKValue: 1
        floatingLeftBound: true
        floatingRightBound: true
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 148
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 12
        mapperMaxClusters: 8
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 100
        mapperRelativeMinScore: 0.8
        mapperMinSeedsDistance: 5
        mapperMaxSeedsDistance: 10
        alignmentStopPenalty: 0
        absoluteMinScore: 194
        relativeMinScore: 0.73
        maxHits: 7
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -20)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    dParameters:
      geneFeatureToAlign: DRegionWithP
      relativeMinScore: 0.85
      absoluteMinScore: 25.0
      maxHits: 3
      scoring:
        type: linear
        alphabet: nucleotide
        subsMatrix: "simple(match = 5, mismatch = -9)"
        gapPenalty: -12
    jParameters:
      geneFeatureToAlign: JRegionWithP
      minSumScore: 150
      relativeMinScore: 0.97
      parameters:
        type: kaligner2
        mapperNValue: 12
        mapperKValue: 1
        floatingLeftBound: true
        floatingRightBound: true
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 134
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 11
        mapperMaxClusters: 12
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 100
        mapperRelativeMinScore: 0.94
        mapperMinSeedsDistance: 6
        mapperMaxSeedsDistance: 8
        alignmentStopPenalty: 0
        absoluteMinScore: 112
        relativeMinScore: 0.78
        maxHits: 3
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -20)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    cParameters:
      geneFeatureToAlign: CExon1
      minSumScore: 40
      relativeMinScore: 0.97
      parameters:
        type: kaligner
        mapperKValue: 11
        floatingLeftBound: false
        floatingRightBound: false
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.75
        mapperMatchScore: 90.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 9
        mapperMaxSeedsDistance: 18
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 22.0
        relativeMinScore: 0.75
        maxHits: 6
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -9)"
          gapPenalty: -12
    vjAlignmentOrder: VThenJ
    libraryStructure: Unknown
    includeDScore: false
    includeCScore: false
    minSumScore: 120.0
    maxHits: 5
    relativeMinVFR3CDR3Score: 0.7
    allowPartialAlignments: false
    allowNoCDR3PartAlignments: false
    allowChimeras: false
    readsLayout: Opposite
    mergerParameters:
      qualityMergingAlgorithm: MaxSubtraction
      partsLayout: null
      minimalOverlap: 13
      minimalMatchQualitySum: 364
      maxQuality: 50
      minimalIdentity: 0.7
      identityType: MinimalQualityWeighted
    fixSeed: true
    alignmentBoundaryTolerance: 5
    minChimeraDetectionScore: 120
    vjOverlapWindow: 3
    saveOriginalSequence: false
    saveOriginalReads: false
    smartForceEdgeAlignments: true
refineTagsAndSort: null
assemblePartial: null
extend: null
assemble:
  sortBySequence: false
  clnaOutput: true
  cellLevel: false
  consensusAssemblerParameters: null
  cloneAssemblerParameters:
    assemblingFeatures:
    - CDR3
    minimalClonalSequenceLength: 12
    qualityAggregationType: Max
    cloneClusteringParameters:
      searchDepth: 2
      allowedMutationsInNRegions: 1
      searchParameters: twoMismatchesOrIndels
      clusteringFilter:
        type: relativeConcentration
        specificMutationProbability: 0.01
    cloneFactoryParameters:
      vParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      jParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      cParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      dParameters:
        relativeMinScore: null
        absoluteMinScore: null
        maxHits: null
        scoring: null
      vdcParameters:
        Variable:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
        Joining:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
        Constant:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
    separateByV: false
    separateByJ: false
    separateByC: false
    maximalPreClusteringRatio: 1.0
    preClusteringScoreFilteringRatio: 2.0
    preClusteringCountFilteringRatio: 2.0
    addReadsCountOnClustering: false
    badQualityThreshold: 0
    maxBadPointsPercent: 0.7
    mappingThreshold: 2of5
    minimalQuality: 15
    postFilters: null
  inferMinRecordsPerConsensus: false
assembleContigs:
  ignoreTags: false
  parameters:
    branchingMinimalQualityShare: 0.1
    branchingMinimalSumQuality: 60
    decisiveBranchingSumQualityThreshold: 120
    alignedSequenceEdgeDelta: 3
    alignmentEdgeRegionSize: 7
    minimalNonEdgePointsFraction: 0.25
    minimalMeanNormalizedQuality: 5.0
    outputMinimalQualityShare: 0.75
    outputMinimalSumQuality: 0
    subCloningRegions: null
    assemblingRegions: null
    postFiltering:
      type: NoFiltering
    trimmingParameters:
      averageQualityThreshold: 10.0
      windowSize: 8
    minimalContigLength: 20
    alignedRegionsOnly: false
exportAlignments:
  chains: ALL
  noHeader: false
  fields:
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -allNFeaturesWithMinQuality
  - field: -allAAFeatures
  - field: -defaultAnchorPoints
exportClones:
  splitByTagType: null
  filterOutOfFrames: false
  filterStops: false
  chains: ALL
  noHeader: false
  fields:
  - field: -cloneId
  - field: -readCount
  - field: -readFraction
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -allNFeaturesWithMinQuality
  - field: -allAAFeatures
  - field: -defaultAnchorPoints
  splitFilesBy:
  - geneLabel:ReliableChain
  groupClonesBy: []

```
 
Much appreciated!
Thanks again!
